-- 04b admin visibility: supporting indexes for the cross-user (fleet-wide)
-- read paths. The existing audit_log / llm_request_cost indexes are all
-- user_id-prefixed (idx_audit_user_time, idx_llm_cost_user_time), so an
-- admin query that scans EVERY user ordered by time cannot use them and
-- degrades to a sequential scan + sort. These two plain time indexes back
-- the admin-only ListAllAuditEvents ordering and the InstanceCostSummary
-- time-window rollup. Members' user-scoped queries are unaffected (they keep
-- hitting the composite user_id-prefixed indexes).
--
-- Do not build idx_audit_time in the transactional startup runner. Production
-- audit_log can be multi-gigabyte; a regular CREATE INDEX can exceed Cloud
-- Run's startup deadline and blocks writes for the duration. Operators should
-- create it separately with:
--
--   CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_audit_time
--       ON audit_log(timestamp DESC);
--
-- The fleet-wide admin routes are OSS-only, so cloud correctness does not
-- depend on this optional performance index.
CREATE INDEX IF NOT EXISTS idx_llm_cost_time ON llm_request_cost(timestamp);
